### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by xxlio109** [gdpl2112/MiraiCallApiPlugin#8]
```
iTX Technologies Mirai Console Loader version 2.1.2-61c8bd8
Runtime: OpenJDK 64-Bit Server VM 17.0.10 (arch: 64)
io.github.Kloping.mirai.p1.CallApiPlugin v3.2
lib-tts-1.1.mirai
已加启动参数
--add-opens java.base/java.lang=ALL-UNNAMED
```
==========================================
使用的模板
```
	"templates":[
		{
			"err":"天气查询失败",
			"out":"<At:$qid>\n$1:$2\n$3:$4\n$5:$6\n",
			"outArgs":["data.forecast[0].date","data.forecast[0].type","data.forecast[1].date","data.forecast[1].type","data.forecast[2].date","data.forecast[2].type"],
			"proxyIp":"",
			"proxyPort":0,
			"sw":true,
			"touch":"未来天气",
			"url":"https://api.vvhan.com/api/weather?city=$1&type=week"
		}
	]
```
==========================================
报错
```
2024-03-19 11:26:12 W/stderr: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.lang.String java.io.File.path accessible: module java.base does not "opens java.io" to unnamed module @7fb9a83c
2024-03-19 11:26:12 W/stderr:   at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
2024-03-19 11:26:12 W/stderr:   at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
2024-03-19 11:26:12 W/stderr:   at java.base/java.lang.reflect.Field.checkCanSetAccessible(Unknown Source)
2024-03-19 11:26:12 W/stderr:   at java.base/java.lang.reflect.Field.setAccessible(Unknown Source)
2024-03-19 11:26:12 W/stderr:   at lib-tts-1.1.mirai.jar//io.github.kloping.serialize.HMLObject.<clinit>(HMLObject.java:41)
2024-03-19 11:26:12 W/stderr:   at MiraiCallApiPlugin-3.2.mirai2.jar//io.github.gdpl2112.mirai.p1.ManagerConf.apply(ManagerConf.java:64)
2024-03-19 11:26:12 W/stderr:   at MiraiCallApiPlugin-3.2.mirai2.jar//io.github.gdpl2112.mirai.p1.ManagerConf.getStateByTouchAndIdDefault(ManagerConf.java:52)
2024-03-19 11:26:12 W/stderr:   at MiraiCallApiPlugin-3.2.mirai2.jar//io.github.gdpl2112.mirai.p1.Worker.enable(Worker.java:117)
2024-03-19 11:26:12 W/stderr:   at MiraiCallApiPlugin-3.2.mirai2.jar//io.github.gdpl2112.mirai.p1.Worker.call(Worker.java:99)
2024-03-19 11:26:12 W/stderr:   at MiraiCallApiPlugin-3.2.mirai2.jar//io.github.gdpl2112.mirai.p1.CallApiPlugin$1.onMessage0(CallApiPlugin.java:75)
2024-03-19 11:26:12 W/stderr:   at MiraiCallApiPlugin-3.2.mirai2.jar//io.github.gdpl2112.mirai.p1.CallApiPlugin$1.onMessage(CallApiPlugin.java:52)
2024-03-19 11:26:12 W/stderr:   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-03-19 11:26:12 W/stderr:   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2024-03-19 11:26:12 W/stderr:   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2024-03-19 11:26:12 W/stderr:   at java.base/java.lang.reflect.Method.invoke(Unknown Source)
2024-03-19 11:26:12 W/stderr:   at net.mamoe.mirai.internal.event.JvmMethodListenersInternal.registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:148)
2024-03-19 11:26:12 W/stderr:   at net.mamoe.mirai.internal.event.JvmMethodListenersInternal.access$registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:26)
2024-03-19 11:26:12 W/stderr:   at net.mamoe.mirai.internal.event.JvmMethodListenersInternal$registerEventHandler$callMethod$2.invokeSuspend(JvmMethodListenersInternal.kt:162)
2024-03-19 11:26:12 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-03-19 11:26:12 W/stderr:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2024-03-19 11:26:12 W/stderr:   at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
2024-03-19 11:26:12 W/stderr:   at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
2024-03-19 11:26:12 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)2024-03-19 11:26:12 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2024-03-19 11:26:12 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
2024-03-19 11:26:12 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2024-03-19 11:26:12 W/stderr: java.lang.NullPointerException: Cannot invoke "com.alibaba.fastjson.JSONObject.getJSONArray(String)" because "jo" is null
2024-03-19 11:26:12 W/stderr:   at MiraiCallApiPlugin-3.2.mirai2.jar//io.github.gdpl2112.mirai.p1.Converter.get0(Converter.java:128)
2024-03-19 11:26:12 W/stderr:   at MiraiCallApiPlugin-3.2.mirai2.jar//io.github.gdpl2112.mirai.p1.Converter.get0(Converter.java:140)
2024-03-19 11:26:12 W/stderr:   at MiraiCallApiPlugin-3.2.mirai2.jar//io.github.gdpl2112.mirai.p1.Converter.get(Converter.java:93)
2024-03-19 11:26:12 W/stderr:   at MiraiCallApiPlugin-3.2.mirai2.jar//io.github.gdpl2112.mirai.p1.Worker.parse(Worker.java:128)
2024-03-19 11:26:12 W/stderr:   at MiraiCallApiPlugin-3.2.mirai2.jar//io.github.gdpl2112.mirai.p1.Worker.call(Worker.java:104)
2024-03-19 11:26:12 W/stderr:   at MiraiCallApiPlugin-3.2.mirai2.jar//io.github.gdpl2112.mirai.p1.CallApiPlugin$1.onMessage0(CallApiPlugin.java:75)
2024-03-19 11:26:12 W/stderr:   at MiraiCallApiPlugin-3.2.mirai2.jar//io.github.gdpl2112.mirai.p1.CallApiPlugin$1.onMessage(CallApiPlugin.java:52)
2024-03-19 11:26:12 W/stderr:   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-03-19 11:26:12 W/stderr:   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2024-03-19 11:26:12 W/stderr:   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2024-03-19 11:26:12 W/stderr:   at java.base/java.lang.reflect.Method.invoke(Unknown Source)
2024-03-19 11:26:12 W/stderr:   at net.mamoe.mirai.internal.event.JvmMethodListenersInternal.registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:148)
2024-03-19 11:26:12 W/stderr:   at net.mamoe.mirai.internal.event.JvmMethodListenersInternal.access$registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:26)
2024-03-19 11:26:12 W/stderr:   at net.mamoe.mirai.internal.event.JvmMethodListenersInternal$registerEventHandler$callMethod$2.invokeSuspend(JvmMethodListenersInternal.kt:162)
2024-03-19 11:26:12 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-03-19 11:26:12 W/stderr:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2024-03-19 11:26:12 W/stderr:   at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
2024-03-19 11:26:12 W/stderr:   at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
2024-03-19 11:26:12 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)2024-03-19 11:26:12 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2024-03-19 11:26:12 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
2024-03-19 11:26:12 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by Kloping** [comment]
降低jdk版本

**Comment by xxlio109** [comment]
已降到
Runtime: OpenJDK 64-Bit Server VM 11 (arch: 64)
```
> WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.github.kloping.serialize.HMLObject (file:/C:/Users/Administrator/Desktop/qqbot/plugins/lib-tts-1.1.mirai.jar) to field java.io.File.path
WARNING: Please consider reporting this to the maintainers of io.github.kloping.serialize.HMLObject
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2024-03-19 19:02:34 W/stderr: https://xxxxxxxxxxxxxxxxxxx加载失败
2024-03-19 19:02:34 W/stderr: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
2024-03-19 19:02:34 W/stderr:   at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:128)
2024-03-19 19:02:34 W/stderr:   at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
2024-03-19 19:02:34 W/stderr:   at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:308)
2024-03-19 19:02:34 W/stderr:   at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:279)
2024-03-19 19:02:34 W/stderr:   at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:181)
2024-03-19 19:02:34 W/stderr:   at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
2024-03-19 19:02:34 W/stderr:   at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
2024-03-19 19:02:34 W/stderr:   at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)2024-03-19 19:02:34 W/stderr:   at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
2024-03-19 19:02:34 W/stderr:   at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
2024-03-19 19:02:34 W/stderr:   at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
2024-03-19 19:02:34 W/stderr:   at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1581)
2024-03-19 19:02:34 W/stderr:   at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
2024-03-19 19:02:34 W/stderr:   at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:245)
2024-03-19 19:02:34 W/stderr:   at java.base/java.net.URL.openStream(URL.java:1117)
2024-03-19 19:02:34 W/stderr:   at MiraiCallApiPlugin-3.2.mirai2.jar//io.github.gdpl2112.mirai.p1.Parse.createImage(Parse.java:179)
2024-03-19 19:02:34 W/stderr:   at MiraiCallApiPlugin-3.2.mirai2.jar//io.github.gdpl2112.mirai.p1.Parse.append(Parse.java:117)
2024-03-19 19:02:34 W/stderr:   at MiraiCallApiPlugin-3.2.mirai2.jar//io.github.gdpl2112.mirai.p1.Parse.getMessageFromString(Parse.java:100)
2024-03-19 19:02:34 W/stderr:   at MiraiCallApiPlugin-3.2.mirai2.jar//io.github.gdpl2112.mirai.p1.Worker.parse(Worker.java:152)
2024-03-19 19:02:34 W/stderr:   at MiraiCallApiPlugin-3.2.mirai2.jar//io.github.gdpl2112.mirai.p1.Worker.call(Worker.java:104)
2024-03-19 19:02:34 W/stderr:   at MiraiCallApiPlugin-3.2.mirai2.jar//io.github.gdpl2112.mirai.p1.CallApiPlugin$1.onMessage0(CallApiPlugin.java:75)
2024-03-19 19:02:34 W/stderr:   at MiraiCallApiPlugin-3.2.mirai2.jar//io.github.gdpl2112.mirai.p1.CallApiPlugin$1.onMessage(CallApiPlugin.java:52)
2024-03-19 19:02:34 W/stderr:   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-03-19 19:02:34 W/stderr:   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2024-03-19 19:02:34 W/stderr:   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-03-19 19:02:34 W/stderr:   at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2024-03-19 19:02:34 W/stderr:   at net.mamoe.mirai.internal.event.JvmMethodListenersInternal.registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:148)
2024-03-19 19:02:34 W/stderr:   at net.mamoe.mirai.internal.event.JvmMethodListenersInternal.access$registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:26)
2024-03-19 19:02:34 W/stderr:   at net.mamoe.mirai.internal.event.JvmMethodListenersInternal$registerEventHandler$callMethod$2.invokeSuspend(JvmMethodListenersInternal.kt:162)
2024-03-19 19:02:34 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-03-19 19:02:34 W/stderr:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2024-03-19 19:02:34 W/stderr:   at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
2024-03-19 19:02:34 W/stderr:   at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
2024-03-19 19:02:34 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)2024-03-19 19:02:34 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2024-03-19 19:02:34 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
2024-03-19 19:02:34 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2024-03-19 19:02:34 W/stderr: java.lang.NullPointerException: Parameter specified as non-null is null: method net.mamoe.mirai.message.data.MessageChainBuilder.append, parameter message
2024-03-19 19:02:34 W/stderr:   at net.mamoe.mirai.message.data.MessageChainBuilder.append(MessageChainBuilder.kt)
2024-03-19 19:02:34 W/stderr:   at MiraiCallApiPlugin-3.2.mirai2.jar//io.github.gdpl2112.mirai.p1.Parse.append(Parse.java:117)
2024-03-19 19:02:34 W/stderr:   at MiraiCallApiPlugin-3.2.mirai2.jar//io.github.gdpl2112.mirai.p1.Parse.getMessageFromString(Parse.java:100)
2024-03-19 19:02:34 W/stderr:   at MiraiCallApiPlugin-3.2.mirai2.jar//io.github.gdpl2112.mirai.p1.Worker.parse(Worker.java:152)
2024-03-19 19:02:34 W/stderr:   at MiraiCallApiPlugin-3.2.mirai2.jar//io.github.gdpl2112.mirai.p1.Worker.call(Worker.java:104)
2024-03-19 19:02:34 W/stderr:   at MiraiCallApiPlugin-3.2.mirai2.jar//io.github.gdpl2112.mirai.p1.CallApiPlugin$1.onMessage0(CallApiPlugin.java:75)
2024-03-19 19:02:34 W/stderr:   at MiraiCallApiPlugin-3.2.mirai2.jar//io.github.gdpl2112.mirai.p1.CallApiPlugin$1.onMessage(CallApiPlugin.java:52)
2024-03-19 19:02:34 W/stderr:   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-03-19 19:02:34 W/stderr:   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2024-03-19 19:02:34 W/stderr:   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-03-19 19:02:34 W/stderr:   at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2024-03-19 19:02:34 W/stderr:   at net.mamoe.mirai.internal.event.JvmMethodListenersInternal.registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:148)
2024-03-19 19:02:34 W/stderr:   at net.mamoe.mirai.internal.event.JvmMethodListenersInternal.access$registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:26)
2024-03-19 19:02:34 W/stderr:   at net.mamoe.mirai.internal.event.JvmMethodListenersInternal$registerEventHandler$callMethod$2.invokeSuspend(JvmMethodListenersInternal.kt:162)
2024-03-19 19:02:34 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-03-19 19:02:34 W/stderr:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2024-03-19 19:02:34 W/stderr:   at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
2024-03-19 19:02:34 W/stderr:   at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
2024-03-19 19:02:34 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)2024-03-19 19:02:34 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2024-03-19 19:02:34 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
2024-03-19 19:02:34 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by Kloping** [comment]
[在这不好交流](https://qm.qq.com/q/N5oFnOBhaS) 方便的话来一下

**Comment by xxlio109** [comment]
我加过很多次了，估计在限制名单那栏，麻烦通过下。

**Comment by Kloping** [comment]
> 我加过很多次了，估计在限制名单那栏，麻烦通过下。

看我主页 邮箱是qq号 加我吧
